backend = "thumb"
color_space = "lab"
palette = "light"
[templates]
waybar = { template = "colors-waybar.css", target = "~/.config/waybar/colors.css" }
rofi = { template = "colors-rofi.rasi", target = "~/.config/rofi/colors.rasi" }
kitty = { template = "colors-kitty.conf", target = "~/.config/kitty/colors.conf" }
hyprland = { template = "colors-hyprland.conf", target = "/home/zek/.config/hypr/colors-wallust.conf" }